In [14]:
import numpy as np

# File Input / Output package

In [15]:
import scipy.io as sio

array = np.ones((5, 5)) # Create 5 x 5, dimensional one's array
sio.savemat('example.mat', {'ar': array}) # save as mat file
data = sio.loadmat('example.mat', struct_as_record=True) #load the file
data['ar']

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Special function

In [30]:
# Cubic Root Function
from scipy import special
arr = np.round(special.cbrt([10, 9, 12, 25]),3)
arr

array([2.154, 2.08 , 2.289, 2.924])

In [39]:
# Exponential Function
arr1 = special.exp10([1,3])
print(arr1)
arr2 = special.exp2([2, 3])
print(arr2)
a = special.sindg(90)
print(a)
b = special.cosdg(45)
print(b)

[  10. 1000.]
[4. 8.]
1.0
0.7071067811865475


In [40]:
# Relative Error Exponential Function
arr2 = special.exprel([-0.1, -0.01, 0, 0.01, 0.1])
arr2

array([0.95162582, 0.99501663, 1.        , 1.00501671, 1.05170918])

In [46]:
# Log Sum Exponential Function
a = np.arange(3)
arr3 = special.logsumexp(a)
arr3

2.4076059644443806

In [50]:
# Lambert Function
w = special.lambertw(1)
w * np.exp(w)

w1 = special.lambertw(1, k=3) # the branches are indexed by the integer k
w1 * np.exp(w1)

(1.0000000000000002+1.6375789613221059e-15j)

In [56]:
# Combintaion & Permutation 
'''If exact is False, then floating point precision is used, 
   otherwise exact long integer is computed.
   If repetition is True, then the number of combinations
   with repetition is computed.'''
arr4 = special.comb(10, 5, exact = False,repetition=True) # Combination

arr5 = special.perm(10, 5, exact = True) #Permutation

In [76]:
arr6 = special.gamma([0, 0.5, 1, 5])
c = 2 + 3j
special.gamma(c)

(-0.08239527266561189+0.0917742874352593j)